package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/Purvig648/graphql-demo/graph/model"
)

// UserSignup is the resolver for the userSignup field.
func (r *mutationResolver) UserSignup(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Service.UserSignup(input)
}

// CreateCompany is the resolver for the CreateCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.NewCompnay) (*model.Company, error) {
	return r.Service.CreateCompany(input)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
